name: Manual File Edit
on:
  workflow_dispatch:

jobs:
  manual:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure folders exist
        run: |
          mkdir -p journals context data-hub/n8n
          echo "# Journal Folder" > journals/README.md
          echo "# Context Folder" > context/README.md
          echo "# Data Hub (n8n)" > data-hub/n8n/README.md

      - name: Commit new or edited files
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add journals context data-hub || true
          git commit -m "manual edit: synced folder structure" || echo "no changes to commit"
          git push
