name: Manual file edit

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Relative file path (e.g., context/history-2025-10-16.md)'
        required: true
        default: 'context/history-YYYY-MM-DD.md'
      mode:
        description: 'append or overwrite'
        required: true
        default: 'overwrite'
      content:
        description: 'Content to write (supports multiline)'
        required: true

jobs:
  edit:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # חשוב: מאפשר כתיבה
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Apply change
        shell: bash
        run: |
          set -euo pipefail
          FILE="${{ github.event.inputs.path }}"
          MODE="${{ github.event.inputs.mode }}"
          mkdir -p "$(dirname "$FILE")"

          if [ "$MODE" = "overwrite" ]; then
            cat > "$FILE" <<'EOF'
${{ github.event.inputs.content }}
EOF
          else
            echo "" >> "$FILE"
            cat >> "$FILE" <<'EOF'
${{ github.event.inputs.content }}
EOF
          fi

      - name: Commit & push (if changed)
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(edit): ${{ github.event.inputs.mode }} ${{
              github.event.inputs.path }}"
            git push
          else
            echo "No changes to commit."
          fi
